/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTagsIndexRouteImport } from './routes/dashboard/tags/index'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardPagesIndexRouteImport } from './routes/dashboard/pages/index'
import { Route as DashboardMediaIndexRouteImport } from './routes/dashboard/media/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as DashboardPostsNewRouteImport } from './routes/dashboard/posts/new'
import { Route as ApiSitemapXmlRouteImport } from './routes/api/sitemap.xml'
import { Route as ApiRssXmlRouteImport } from './routes/api/rss.xml'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicDemoBetterAuthRouteImport } from './routes/_public/demo/better-auth'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog/$slug'
import { Route as DashboardPostsPostIdEditRouteImport } from './routes/dashboard/posts/$postId.edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTagsIndexRoute = DashboardTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagesIndexRoute = DashboardPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMediaIndexRoute = DashboardMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardPostsNewRoute = DashboardPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSitemapXmlRoute = ApiSitemapXmlRouteImport.update({
  id: '/api/sitemap/xml',
  path: '/api/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRssXmlRoute = ApiRssXmlRouteImport.update({
  id: '/api/rss/xml',
  path: '/api/rss/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDemoBetterAuthRoute = PublicDemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardPostsPostIdEditRoute =
  DashboardPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/demo/better-auth': typeof PublicDemoBetterAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/rss/xml': typeof ApiRssXmlRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/media/': typeof DashboardMediaIndexRoute
  '/dashboard/pages/': typeof DashboardPagesIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/tags/': typeof DashboardTagsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/demo/better-auth': typeof PublicDemoBetterAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/rss/xml': typeof ApiRssXmlRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/blog': typeof PublicBlogIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/media': typeof DashboardMediaIndexRoute
  '/dashboard/pages': typeof DashboardPagesIndexRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/tags': typeof DashboardTagsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/demo/better-auth': typeof PublicDemoBetterAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/rss/xml': typeof ApiRssXmlRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/media/': typeof DashboardMediaIndexRoute
  '/dashboard/pages/': typeof DashboardPagesIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/tags/': typeof DashboardTagsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/blog/$slug'
    | '/demo/better-auth'
    | '/api/auth/$'
    | '/api/media/$'
    | '/api/rss/xml'
    | '/api/sitemap/xml'
    | '/dashboard/posts/new'
    | '/blog/'
    | '/dashboard/categories/'
    | '/dashboard/media/'
    | '/dashboard/pages/'
    | '/dashboard/posts/'
    | '/dashboard/tags/'
    | '/dashboard/users/'
    | '/dashboard/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard/settings'
    | '/'
    | '/dashboard'
    | '/blog/$slug'
    | '/demo/better-auth'
    | '/api/auth/$'
    | '/api/media/$'
    | '/api/rss/xml'
    | '/api/sitemap/xml'
    | '/dashboard/posts/new'
    | '/blog'
    | '/dashboard/categories'
    | '/dashboard/media'
    | '/dashboard/pages'
    | '/dashboard/posts'
    | '/dashboard/tags'
    | '/dashboard/users'
    | '/dashboard/posts/$postId/edit'
  id:
    | '__root__'
    | '/_public'
    | '/dashboard'
    | '/_public/about'
    | '/dashboard/settings'
    | '/_public/'
    | '/dashboard/'
    | '/_public/blog/$slug'
    | '/_public/demo/better-auth'
    | '/api/auth/$'
    | '/api/media/$'
    | '/api/rss/xml'
    | '/api/sitemap/xml'
    | '/dashboard/posts/new'
    | '/_public/blog/'
    | '/dashboard/categories/'
    | '/dashboard/media/'
    | '/dashboard/pages/'
    | '/dashboard/posts/'
    | '/dashboard/tags/'
    | '/dashboard/users/'
    | '/dashboard/posts/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  ApiRssXmlRoute: typeof ApiRssXmlRoute
  ApiSitemapXmlRoute: typeof ApiSitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tags/': {
      id: '/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags/'
      preLoaderRoute: typeof DashboardTagsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pages/': {
      id: '/dashboard/pages/'
      path: '/pages'
      fullPath: '/dashboard/pages/'
      preLoaderRoute: typeof DashboardPagesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media/': {
      id: '/dashboard/media/'
      path: '/media'
      fullPath: '/dashboard/media/'
      preLoaderRoute: typeof DashboardMediaIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/posts/new': {
      id: '/dashboard/posts/new'
      path: '/posts/new'
      fullPath: '/dashboard/posts/new'
      preLoaderRoute: typeof DashboardPostsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/sitemap/xml': {
      id: '/api/sitemap/xml'
      path: '/api/sitemap/xml'
      fullPath: '/api/sitemap/xml'
      preLoaderRoute: typeof ApiSitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rss/xml': {
      id: '/api/rss/xml'
      path: '/api/rss/xml'
      fullPath: '/api/rss/xml'
      preLoaderRoute: typeof ApiRssXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/demo/better-auth': {
      id: '/_public/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof PublicDemoBetterAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/posts/$postId/edit': {
      id: '/dashboard/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/dashboard/posts/$postId/edit'
      preLoaderRoute: typeof DashboardPostsPostIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicDemoBetterAuthRoute: typeof PublicDemoBetterAuthRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicDemoBetterAuthRoute: PublicDemoBetterAuthRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPostsNewRoute: typeof DashboardPostsNewRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardMediaIndexRoute: typeof DashboardMediaIndexRoute
  DashboardPagesIndexRoute: typeof DashboardPagesIndexRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardTagsIndexRoute: typeof DashboardTagsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardPostsPostIdEditRoute: typeof DashboardPostsPostIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPostsNewRoute: DashboardPostsNewRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardMediaIndexRoute: DashboardMediaIndexRoute,
  DashboardPagesIndexRoute: DashboardPagesIndexRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardTagsIndexRoute: DashboardTagsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardPostsPostIdEditRoute: DashboardPostsPostIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  ApiRssXmlRoute: ApiRssXmlRoute,
  ApiSitemapXmlRoute: ApiSitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
