/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RssXmlRouteImport } from './routes/rss.xml'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAuthRouteImport } from './routes/_public/auth'
import { Route as PublicAccountRouteImport } from './routes/_public/account'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as DashboardWebhooksIndexRouteImport } from './routes/dashboard/webhooks/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTagsIndexRouteImport } from './routes/dashboard/tags/index'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardPagesIndexRouteImport } from './routes/dashboard/pages/index'
import { Route as DashboardNewslettersIndexRouteImport } from './routes/dashboard/newsletters/index'
import { Route as DashboardMediaIndexRouteImport } from './routes/dashboard/media/index'
import { Route as DashboardCommentsIndexRouteImport } from './routes/dashboard/comments/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as DashboardWebhooksNewRouteImport } from './routes/dashboard/webhooks/new'
import { Route as DashboardUsersSubscribersRouteImport } from './routes/dashboard/users/subscribers'
import { Route as DashboardPostsNewRouteImport } from './routes/dashboard/posts/new'
import { Route as DashboardNewslettersNewRouteImport } from './routes/dashboard/newsletters/new'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiNewsletterUnsubscribeRouteImport } from './routes/api/newsletter/unsubscribe'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media.$'
import { Route as ApiIngestSplatRouteImport } from './routes/api/ingest.$'
import { Route as ApiExportPostsRouteImport } from './routes/api/export/posts'
import { Route as ApiCronPublishRouteImport } from './routes/api/cron.publish'
import { Route as ApiCommentsIdRouteImport } from './routes/api/comments.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog/$slug'
import { Route as PublicAuthResetPasswordRouteImport } from './routes/_public/auth/reset-password'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/auth/forgot-password'
import { Route as DashboardPostsPostIdEditRouteImport } from './routes/dashboard/posts/$postId.edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssXmlRoute = RssXmlRouteImport.update({
  id: '/rss/xml',
  path: '/rss/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAccountRoute = PublicAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardWebhooksIndexRoute = DashboardWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTagsIndexRoute = DashboardTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagesIndexRoute = DashboardPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewslettersIndexRoute =
  DashboardNewslettersIndexRouteImport.update({
    id: '/newsletters/',
    path: '/newsletters/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMediaIndexRoute = DashboardMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommentsIndexRoute = DashboardCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardWebhooksNewRoute = DashboardWebhooksNewRouteImport.update({
  id: '/webhooks/new',
  path: '/webhooks/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersSubscribersRoute =
  DashboardUsersSubscribersRouteImport.update({
    id: '/users/subscribers',
    path: '/users/subscribers',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPostsNewRoute = DashboardPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewslettersNewRoute = DashboardNewslettersNewRouteImport.update({
  id: '/newsletters/new',
  path: '/newsletters/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterUnsubscribeRoute =
  ApiNewsletterUnsubscribeRouteImport.update({
    id: '/api/newsletter/unsubscribe',
    path: '/api/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestSplatRoute = ApiIngestSplatRouteImport.update({
  id: '/api/ingest/$',
  path: '/api/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportPostsRoute = ApiExportPostsRouteImport.update({
  id: '/api/export/posts',
  path: '/api/export/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPublishRoute = ApiCronPublishRouteImport.update({
  id: '/api/cron/publish',
  path: '/api/cron/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsIdRoute = ApiCommentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthResetPasswordRoute = PublicAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => PublicAuthRoute,
  } as any)
const DashboardPostsPostIdEditRoute =
  DashboardPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/account': typeof PublicAccountRoute
  '/auth': typeof PublicAuthRouteWithChildren
  '/contact': typeof PublicContactRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comments/$id': typeof ApiCommentsIdRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/export/posts': typeof ApiExportPostsRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/newsletters/new': typeof DashboardNewslettersNewRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/users/subscribers': typeof DashboardUsersSubscribersRoute
  '/dashboard/webhooks/new': typeof DashboardWebhooksNewRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/comments/': typeof DashboardCommentsIndexRoute
  '/dashboard/media/': typeof DashboardMediaIndexRoute
  '/dashboard/newsletters/': typeof DashboardNewslettersIndexRoute
  '/dashboard/pages/': typeof DashboardPagesIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/tags/': typeof DashboardTagsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/webhooks/': typeof DashboardWebhooksIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/account': typeof PublicAccountRoute
  '/auth': typeof PublicAuthRouteWithChildren
  '/contact': typeof PublicContactRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comments/$id': typeof ApiCommentsIdRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/export/posts': typeof ApiExportPostsRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/newsletters/new': typeof DashboardNewslettersNewRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/users/subscribers': typeof DashboardUsersSubscribersRoute
  '/dashboard/webhooks/new': typeof DashboardWebhooksNewRoute
  '/blog': typeof PublicBlogIndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/comments': typeof DashboardCommentsIndexRoute
  '/dashboard/media': typeof DashboardMediaIndexRoute
  '/dashboard/newsletters': typeof DashboardNewslettersIndexRoute
  '/dashboard/pages': typeof DashboardPagesIndexRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/tags': typeof DashboardTagsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/webhooks': typeof DashboardWebhooksIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/account': typeof PublicAccountRoute
  '/_public/auth': typeof PublicAuthRouteWithChildren
  '/_public/contact': typeof PublicContactRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/register': typeof PublicAuthRegisterRoute
  '/_public/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comments/$id': typeof ApiCommentsIdRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/export/posts': typeof ApiExportPostsRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/newsletters/new': typeof DashboardNewslettersNewRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/users/subscribers': typeof DashboardUsersSubscribersRoute
  '/dashboard/webhooks/new': typeof DashboardWebhooksNewRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/comments/': typeof DashboardCommentsIndexRoute
  '/dashboard/media/': typeof DashboardMediaIndexRoute
  '/dashboard/newsletters/': typeof DashboardNewslettersIndexRoute
  '/dashboard/pages/': typeof DashboardPagesIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/tags/': typeof DashboardTagsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/webhooks/': typeof DashboardWebhooksIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/account'
    | '/auth'
    | '/contact'
    | '/api/comments'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/dashboard/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/api/auth/$'
    | '/api/comments/$id'
    | '/api/cron/publish'
    | '/api/export/posts'
    | '/api/ingest/$'
    | '/api/media/$'
    | '/api/newsletter/unsubscribe'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/dashboard/newsletters/new'
    | '/dashboard/posts/new'
    | '/dashboard/users/subscribers'
    | '/dashboard/webhooks/new'
    | '/blog/'
    | '/dashboard/analytics/'
    | '/dashboard/categories/'
    | '/dashboard/comments/'
    | '/dashboard/media/'
    | '/dashboard/newsletters/'
    | '/dashboard/pages/'
    | '/dashboard/posts/'
    | '/dashboard/tags/'
    | '/dashboard/users/'
    | '/dashboard/webhooks/'
    | '/dashboard/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/account'
    | '/auth'
    | '/contact'
    | '/api/comments'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/api/auth/$'
    | '/api/comments/$id'
    | '/api/cron/publish'
    | '/api/export/posts'
    | '/api/ingest/$'
    | '/api/media/$'
    | '/api/newsletter/unsubscribe'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/dashboard/newsletters/new'
    | '/dashboard/posts/new'
    | '/dashboard/users/subscribers'
    | '/dashboard/webhooks/new'
    | '/blog'
    | '/dashboard/analytics'
    | '/dashboard/categories'
    | '/dashboard/comments'
    | '/dashboard/media'
    | '/dashboard/newsletters'
    | '/dashboard/pages'
    | '/dashboard/posts'
    | '/dashboard/tags'
    | '/dashboard/users'
    | '/dashboard/webhooks'
    | '/dashboard/posts/$postId/edit'
  id:
    | '__root__'
    | '/_public'
    | '/dashboard'
    | '/_public/about'
    | '/_public/account'
    | '/_public/auth'
    | '/_public/contact'
    | '/api/comments'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/_public/'
    | '/dashboard/'
    | '/_public/auth/forgot-password'
    | '/_public/auth/login'
    | '/_public/auth/register'
    | '/_public/auth/reset-password'
    | '/_public/blog/$slug'
    | '/api/auth/$'
    | '/api/comments/$id'
    | '/api/cron/publish'
    | '/api/export/posts'
    | '/api/ingest/$'
    | '/api/media/$'
    | '/api/newsletter/unsubscribe'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/dashboard/newsletters/new'
    | '/dashboard/posts/new'
    | '/dashboard/users/subscribers'
    | '/dashboard/webhooks/new'
    | '/_public/blog/'
    | '/dashboard/analytics/'
    | '/dashboard/categories/'
    | '/dashboard/comments/'
    | '/dashboard/media/'
    | '/dashboard/newsletters/'
    | '/dashboard/pages/'
    | '/dashboard/posts/'
    | '/dashboard/tags/'
    | '/dashboard/users/'
    | '/dashboard/webhooks/'
    | '/dashboard/posts/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiCommentsRoute: typeof ApiCommentsRouteWithChildren
  RssXmlRoute: typeof RssXmlRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronPublishRoute: typeof ApiCronPublishRoute
  ApiExportPostsRoute: typeof ApiExportPostsRoute
  ApiIngestSplatRoute: typeof ApiIngestSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  ApiNewsletterUnsubscribeRoute: typeof ApiNewsletterUnsubscribeRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/xml': {
      id: '/rss/xml'
      path: '/rss/xml'
      fullPath: '/rss/xml'
      preLoaderRoute: typeof RssXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/account': {
      id: '/_public/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof PublicAccountRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/webhooks/': {
      id: '/dashboard/webhooks/'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks/'
      preLoaderRoute: typeof DashboardWebhooksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tags/': {
      id: '/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags/'
      preLoaderRoute: typeof DashboardTagsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pages/': {
      id: '/dashboard/pages/'
      path: '/pages'
      fullPath: '/dashboard/pages/'
      preLoaderRoute: typeof DashboardPagesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/newsletters/': {
      id: '/dashboard/newsletters/'
      path: '/newsletters'
      fullPath: '/dashboard/newsletters/'
      preLoaderRoute: typeof DashboardNewslettersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media/': {
      id: '/dashboard/media/'
      path: '/media'
      fullPath: '/dashboard/media/'
      preLoaderRoute: typeof DashboardMediaIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/comments/': {
      id: '/dashboard/comments/'
      path: '/comments'
      fullPath: '/dashboard/comments/'
      preLoaderRoute: typeof DashboardCommentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/webhooks/new': {
      id: '/dashboard/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/dashboard/webhooks/new'
      preLoaderRoute: typeof DashboardWebhooksNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/subscribers': {
      id: '/dashboard/users/subscribers'
      path: '/users/subscribers'
      fullPath: '/dashboard/users/subscribers'
      preLoaderRoute: typeof DashboardUsersSubscribersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts/new': {
      id: '/dashboard/posts/new'
      path: '/posts/new'
      fullPath: '/dashboard/posts/new'
      preLoaderRoute: typeof DashboardPostsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/newsletters/new': {
      id: '/dashboard/newsletters/new'
      path: '/newsletters/new'
      fullPath: '/dashboard/newsletters/new'
      preLoaderRoute: typeof DashboardNewslettersNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/unsubscribe': {
      id: '/api/newsletter/unsubscribe'
      path: '/api/newsletter/unsubscribe'
      fullPath: '/api/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/$': {
      id: '/api/ingest/$'
      path: '/api/ingest/$'
      fullPath: '/api/ingest/$'
      preLoaderRoute: typeof ApiIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/posts': {
      id: '/api/export/posts'
      path: '/api/export/posts'
      fullPath: '/api/export/posts'
      preLoaderRoute: typeof ApiExportPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/publish': {
      id: '/api/cron/publish'
      path: '/api/cron/publish'
      fullPath: '/api/cron/publish'
      preLoaderRoute: typeof ApiCronPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments/$id': {
      id: '/api/comments/$id'
      path: '/$id'
      fullPath: '/api/comments/$id'
      preLoaderRoute: typeof ApiCommentsIdRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/reset-password': {
      id: '/_public/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof PublicAuthResetPasswordRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/register': {
      id: '/_public/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/forgot-password': {
      id: '/_public/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/dashboard/posts/$postId/edit': {
      id: '/dashboard/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/dashboard/posts/$postId/edit'
      preLoaderRoute: typeof DashboardPostsPostIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface PublicAuthRouteChildren {
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicAuthResetPasswordRoute: typeof PublicAuthResetPasswordRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthResetPasswordRoute: PublicAuthResetPasswordRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAccountRoute: typeof PublicAccountRoute
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicContactRoute: typeof PublicContactRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAccountRoute: PublicAccountRoute,
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicContactRoute: PublicContactRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardRouteChildren {
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardNewslettersNewRoute: typeof DashboardNewslettersNewRoute
  DashboardPostsNewRoute: typeof DashboardPostsNewRoute
  DashboardUsersSubscribersRoute: typeof DashboardUsersSubscribersRoute
  DashboardWebhooksNewRoute: typeof DashboardWebhooksNewRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardCommentsIndexRoute: typeof DashboardCommentsIndexRoute
  DashboardMediaIndexRoute: typeof DashboardMediaIndexRoute
  DashboardNewslettersIndexRoute: typeof DashboardNewslettersIndexRoute
  DashboardPagesIndexRoute: typeof DashboardPagesIndexRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardTagsIndexRoute: typeof DashboardTagsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardWebhooksIndexRoute: typeof DashboardWebhooksIndexRoute
  DashboardPostsPostIdEditRoute: typeof DashboardPostsPostIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardNewslettersNewRoute: DashboardNewslettersNewRoute,
  DashboardPostsNewRoute: DashboardPostsNewRoute,
  DashboardUsersSubscribersRoute: DashboardUsersSubscribersRoute,
  DashboardWebhooksNewRoute: DashboardWebhooksNewRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardCommentsIndexRoute: DashboardCommentsIndexRoute,
  DashboardMediaIndexRoute: DashboardMediaIndexRoute,
  DashboardNewslettersIndexRoute: DashboardNewslettersIndexRoute,
  DashboardPagesIndexRoute: DashboardPagesIndexRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardTagsIndexRoute: DashboardTagsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardWebhooksIndexRoute: DashboardWebhooksIndexRoute,
  DashboardPostsPostIdEditRoute: DashboardPostsPostIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiCommentsRouteChildren {
  ApiCommentsIdRoute: typeof ApiCommentsIdRoute
}

const ApiCommentsRouteChildren: ApiCommentsRouteChildren = {
  ApiCommentsIdRoute: ApiCommentsIdRoute,
}

const ApiCommentsRouteWithChildren = ApiCommentsRoute._addFileChildren(
  ApiCommentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiCommentsRoute: ApiCommentsRouteWithChildren,
  RssXmlRoute: RssXmlRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronPublishRoute: ApiCronPublishRoute,
  ApiExportPostsRoute: ApiExportPostsRoute,
  ApiIngestSplatRoute: ApiIngestSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  ApiNewsletterUnsubscribeRoute: ApiNewsletterUnsubscribeRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
