/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RssXmlRouteImport } from './routes/rss.xml'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRedirectsRouteImport } from './routes/dashboard/redirects'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardMenusRouteImport } from './routes/dashboard/menus'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAuthRouteImport } from './routes/_public/auth'
import { Route as PublicAccountRouteImport } from './routes/_public/account'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as DashboardWebhooksIndexRouteImport } from './routes/dashboard/webhooks/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTagsIndexRouteImport } from './routes/dashboard/tags/index'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardPagesIndexRouteImport } from './routes/dashboard/pages/index'
import { Route as DashboardNewslettersIndexRouteImport } from './routes/dashboard/newsletters/index'
import { Route as DashboardMediaIndexRouteImport } from './routes/dashboard/media/index'
import { Route as DashboardCommentsIndexRouteImport } from './routes/dashboard/comments/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as DashboardWebhooksNewRouteImport } from './routes/dashboard/webhooks/new'
import { Route as DashboardUsersSubscribersRouteImport } from './routes/dashboard/users/subscribers'
import { Route as DashboardPostsNewRouteImport } from './routes/dashboard/posts/new'
import { Route as DashboardPagesNewRouteImport } from './routes/dashboard/pages/new'
import { Route as DashboardNewslettersNewRouteImport } from './routes/dashboard/newsletters/new'
import { Route as DashboardNewslettersNewsletterIdRouteImport } from './routes/dashboard/newsletters/$newsletterId'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiStripeBillingPortalRouteImport } from './routes/api/stripe/billing-portal'
import { Route as ApiNewsletterWebhookRouteImport } from './routes/api/newsletter/webhook'
import { Route as ApiNewsletterUnsubscribeRouteImport } from './routes/api/newsletter/unsubscribe'
import { Route as ApiNewsletterOpenRouteImport } from './routes/api/newsletter/open'
import { Route as ApiNewsletterConfirmRouteImport } from './routes/api/newsletter/confirm'
import { Route as ApiNewsletterClickRouteImport } from './routes/api/newsletter/click'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media.$'
import { Route as ApiIngestSplatRouteImport } from './routes/api/ingest.$'
import { Route as ApiHealthReadinessRouteImport } from './routes/api/health.readiness'
import { Route as ApiHealthDependenciesRouteImport } from './routes/api/health.dependencies'
import { Route as ApiExportPostsRouteImport } from './routes/api/export/posts'
import { Route as ApiCronPublishRouteImport } from './routes/api/cron.publish'
import { Route as ApiCommentsIdRouteImport } from './routes/api/comments.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog/$slug'
import { Route as PublicAuthorSlugRouteImport } from './routes/_public/author/$slug'
import { Route as PublicAuthResetPasswordRouteImport } from './routes/_public/auth/reset-password'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/auth/forgot-password'
import { Route as DashboardPreviewPostPostIdRouteImport } from './routes/dashboard/preview/post.$postId'
import { Route as DashboardPreviewPagePageIdRouteImport } from './routes/dashboard/preview/page.$pageId'
import { Route as DashboardPostsPostIdEditRouteImport } from './routes/dashboard/posts/$postId.edit'
import { Route as DashboardPagesPageIdEditRouteImport } from './routes/dashboard/pages/$pageId.edit'
import { Route as PublicBlogTagSlugRouteImport } from './routes/_public/blog/tag/$slug'
import { Route as PublicBlogCategorySlugRouteImport } from './routes/_public/blog/category/$slug'
import { Route as PublicAuthInviteTokenRouteImport } from './routes/_public/auth/invite.$token'
import { Route as PublicBlogArchiveYearIndexRouteImport } from './routes/_public/blog/archive/$year/index'
import { Route as PublicBlogArchiveYearMonthRouteImport } from './routes/_public/blog/archive/$year/$month'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssXmlRoute = RssXmlRouteImport.update({
  id: '/rss/xml',
  path: '/rss/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRedirectsRoute = DashboardRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenusRoute = DashboardMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAccountRoute = PublicAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardWebhooksIndexRoute = DashboardWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTagsIndexRoute = DashboardTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagesIndexRoute = DashboardPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewslettersIndexRoute =
  DashboardNewslettersIndexRouteImport.update({
    id: '/newsletters/',
    path: '/newsletters/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMediaIndexRoute = DashboardMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommentsIndexRoute = DashboardCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardWebhooksNewRoute = DashboardWebhooksNewRouteImport.update({
  id: '/webhooks/new',
  path: '/webhooks/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersSubscribersRoute =
  DashboardUsersSubscribersRouteImport.update({
    id: '/users/subscribers',
    path: '/users/subscribers',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPostsNewRoute = DashboardPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagesNewRoute = DashboardPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewslettersNewRoute = DashboardNewslettersNewRouteImport.update({
  id: '/newsletters/new',
  path: '/newsletters/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewslettersNewsletterIdRoute =
  DashboardNewslettersNewsletterIdRouteImport.update({
    id: '/newsletters/$newsletterId',
    path: '/newsletters/$newsletterId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeBillingPortalRoute = ApiStripeBillingPortalRouteImport.update({
  id: '/api/stripe/billing-portal',
  path: '/api/stripe/billing-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterWebhookRoute = ApiNewsletterWebhookRouteImport.update({
  id: '/api/newsletter/webhook',
  path: '/api/newsletter/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterUnsubscribeRoute =
  ApiNewsletterUnsubscribeRouteImport.update({
    id: '/api/newsletter/unsubscribe',
    path: '/api/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNewsletterOpenRoute = ApiNewsletterOpenRouteImport.update({
  id: '/api/newsletter/open',
  path: '/api/newsletter/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterConfirmRoute = ApiNewsletterConfirmRouteImport.update({
  id: '/api/newsletter/confirm',
  path: '/api/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterClickRoute = ApiNewsletterClickRouteImport.update({
  id: '/api/newsletter/click',
  path: '/api/newsletter/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestSplatRoute = ApiIngestSplatRouteImport.update({
  id: '/api/ingest/$',
  path: '/api/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadinessRoute = ApiHealthReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthDependenciesRoute = ApiHealthDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiExportPostsRoute = ApiExportPostsRouteImport.update({
  id: '/api/export/posts',
  path: '/api/export/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPublishRoute = ApiCronPublishRouteImport.update({
  id: '/api/cron/publish',
  path: '/api/cron/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsIdRoute = ApiCommentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthorSlugRoute = PublicAuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthResetPasswordRoute = PublicAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => PublicAuthRoute,
  } as any)
const DashboardPreviewPostPostIdRoute =
  DashboardPreviewPostPostIdRouteImport.update({
    id: '/preview/post/$postId',
    path: '/preview/post/$postId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPreviewPagePageIdRoute =
  DashboardPreviewPagePageIdRouteImport.update({
    id: '/preview/page/$pageId',
    path: '/preview/page/$pageId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPostsPostIdEditRoute =
  DashboardPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPagesPageIdEditRoute =
  DashboardPagesPageIdEditRouteImport.update({
    id: '/pages/$pageId/edit',
    path: '/pages/$pageId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const PublicBlogTagSlugRoute = PublicBlogTagSlugRouteImport.update({
  id: '/blog/tag/$slug',
  path: '/blog/tag/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogCategorySlugRoute = PublicBlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthInviteTokenRoute = PublicAuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicBlogArchiveYearIndexRoute =
  PublicBlogArchiveYearIndexRouteImport.update({
    id: '/blog/archive/$year/',
    path: '/blog/archive/$year/',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicBlogArchiveYearMonthRoute =
  PublicBlogArchiveYearMonthRouteImport.update({
    id: '/blog/archive/$year/$month',
    path: '/blog/archive/$year/$month',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/$': typeof PublicSplatRoute
  '/about': typeof PublicAboutRoute
  '/account': typeof PublicAccountRoute
  '/auth': typeof PublicAuthRouteWithChildren
  '/contact': typeof PublicContactRoute
  '/pricing': typeof PublicPricingRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/health': typeof ApiHealthRouteWithChildren
  '/dashboard/menus': typeof DashboardMenusRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/redirects': typeof DashboardRedirectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/author/$slug': typeof PublicAuthorSlugRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comments/$id': typeof ApiCommentsIdRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/export/posts': typeof ApiExportPostsRoute
  '/api/health/dependencies': typeof ApiHealthDependenciesRoute
  '/api/health/readiness': typeof ApiHealthReadinessRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/newsletter/click': typeof ApiNewsletterClickRoute
  '/api/newsletter/confirm': typeof ApiNewsletterConfirmRoute
  '/api/newsletter/open': typeof ApiNewsletterOpenRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/api/newsletter/webhook': typeof ApiNewsletterWebhookRoute
  '/api/stripe/billing-portal': typeof ApiStripeBillingPortalRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/newsletters/$newsletterId': typeof DashboardNewslettersNewsletterIdRoute
  '/dashboard/newsletters/new': typeof DashboardNewslettersNewRoute
  '/dashboard/pages/new': typeof DashboardPagesNewRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/users/subscribers': typeof DashboardUsersSubscribersRoute
  '/dashboard/webhooks/new': typeof DashboardWebhooksNewRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/comments/': typeof DashboardCommentsIndexRoute
  '/dashboard/media/': typeof DashboardMediaIndexRoute
  '/dashboard/newsletters/': typeof DashboardNewslettersIndexRoute
  '/dashboard/pages/': typeof DashboardPagesIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/tags/': typeof DashboardTagsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/webhooks/': typeof DashboardWebhooksIndexRoute
  '/auth/invite/$token': typeof PublicAuthInviteTokenRoute
  '/blog/category/$slug': typeof PublicBlogCategorySlugRoute
  '/blog/tag/$slug': typeof PublicBlogTagSlugRoute
  '/dashboard/pages/$pageId/edit': typeof DashboardPagesPageIdEditRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
  '/dashboard/preview/page/$pageId': typeof DashboardPreviewPagePageIdRoute
  '/dashboard/preview/post/$postId': typeof DashboardPreviewPostPostIdRoute
  '/blog/archive/$year/$month': typeof PublicBlogArchiveYearMonthRoute
  '/blog/archive/$year/': typeof PublicBlogArchiveYearIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof PublicSplatRoute
  '/about': typeof PublicAboutRoute
  '/account': typeof PublicAccountRoute
  '/auth': typeof PublicAuthRouteWithChildren
  '/contact': typeof PublicContactRoute
  '/pricing': typeof PublicPricingRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/health': typeof ApiHealthRouteWithChildren
  '/dashboard/menus': typeof DashboardMenusRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/redirects': typeof DashboardRedirectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/author/$slug': typeof PublicAuthorSlugRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comments/$id': typeof ApiCommentsIdRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/export/posts': typeof ApiExportPostsRoute
  '/api/health/dependencies': typeof ApiHealthDependenciesRoute
  '/api/health/readiness': typeof ApiHealthReadinessRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/newsletter/click': typeof ApiNewsletterClickRoute
  '/api/newsletter/confirm': typeof ApiNewsletterConfirmRoute
  '/api/newsletter/open': typeof ApiNewsletterOpenRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/api/newsletter/webhook': typeof ApiNewsletterWebhookRoute
  '/api/stripe/billing-portal': typeof ApiStripeBillingPortalRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/newsletters/$newsletterId': typeof DashboardNewslettersNewsletterIdRoute
  '/dashboard/newsletters/new': typeof DashboardNewslettersNewRoute
  '/dashboard/pages/new': typeof DashboardPagesNewRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/users/subscribers': typeof DashboardUsersSubscribersRoute
  '/dashboard/webhooks/new': typeof DashboardWebhooksNewRoute
  '/blog': typeof PublicBlogIndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/comments': typeof DashboardCommentsIndexRoute
  '/dashboard/media': typeof DashboardMediaIndexRoute
  '/dashboard/newsletters': typeof DashboardNewslettersIndexRoute
  '/dashboard/pages': typeof DashboardPagesIndexRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/tags': typeof DashboardTagsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/webhooks': typeof DashboardWebhooksIndexRoute
  '/auth/invite/$token': typeof PublicAuthInviteTokenRoute
  '/blog/category/$slug': typeof PublicBlogCategorySlugRoute
  '/blog/tag/$slug': typeof PublicBlogTagSlugRoute
  '/dashboard/pages/$pageId/edit': typeof DashboardPagesPageIdEditRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
  '/dashboard/preview/page/$pageId': typeof DashboardPreviewPagePageIdRoute
  '/dashboard/preview/post/$postId': typeof DashboardPreviewPostPostIdRoute
  '/blog/archive/$year/$month': typeof PublicBlogArchiveYearMonthRoute
  '/blog/archive/$year': typeof PublicBlogArchiveYearIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_public/$': typeof PublicSplatRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/account': typeof PublicAccountRoute
  '/_public/auth': typeof PublicAuthRouteWithChildren
  '/_public/contact': typeof PublicContactRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/health': typeof ApiHealthRouteWithChildren
  '/dashboard/menus': typeof DashboardMenusRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/redirects': typeof DashboardRedirectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/register': typeof PublicAuthRegisterRoute
  '/_public/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/_public/author/$slug': typeof PublicAuthorSlugRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comments/$id': typeof ApiCommentsIdRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/export/posts': typeof ApiExportPostsRoute
  '/api/health/dependencies': typeof ApiHealthDependenciesRoute
  '/api/health/readiness': typeof ApiHealthReadinessRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/newsletter/click': typeof ApiNewsletterClickRoute
  '/api/newsletter/confirm': typeof ApiNewsletterConfirmRoute
  '/api/newsletter/open': typeof ApiNewsletterOpenRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/api/newsletter/webhook': typeof ApiNewsletterWebhookRoute
  '/api/stripe/billing-portal': typeof ApiStripeBillingPortalRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/newsletters/$newsletterId': typeof DashboardNewslettersNewsletterIdRoute
  '/dashboard/newsletters/new': typeof DashboardNewslettersNewRoute
  '/dashboard/pages/new': typeof DashboardPagesNewRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/users/subscribers': typeof DashboardUsersSubscribersRoute
  '/dashboard/webhooks/new': typeof DashboardWebhooksNewRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/comments/': typeof DashboardCommentsIndexRoute
  '/dashboard/media/': typeof DashboardMediaIndexRoute
  '/dashboard/newsletters/': typeof DashboardNewslettersIndexRoute
  '/dashboard/pages/': typeof DashboardPagesIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/tags/': typeof DashboardTagsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/webhooks/': typeof DashboardWebhooksIndexRoute
  '/_public/auth/invite/$token': typeof PublicAuthInviteTokenRoute
  '/_public/blog/category/$slug': typeof PublicBlogCategorySlugRoute
  '/_public/blog/tag/$slug': typeof PublicBlogTagSlugRoute
  '/dashboard/pages/$pageId/edit': typeof DashboardPagesPageIdEditRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
  '/dashboard/preview/page/$pageId': typeof DashboardPreviewPagePageIdRoute
  '/dashboard/preview/post/$postId': typeof DashboardPreviewPostPostIdRoute
  '/_public/blog/archive/$year/$month': typeof PublicBlogArchiveYearMonthRoute
  '/_public/blog/archive/$year/': typeof PublicBlogArchiveYearIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$'
    | '/about'
    | '/account'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/api/comments'
    | '/api/health'
    | '/dashboard/menus'
    | '/dashboard/messages'
    | '/dashboard/redirects'
    | '/dashboard/settings'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/dashboard/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/author/$slug'
    | '/blog/$slug'
    | '/api/auth/$'
    | '/api/comments/$id'
    | '/api/cron/publish'
    | '/api/export/posts'
    | '/api/health/dependencies'
    | '/api/health/readiness'
    | '/api/ingest/$'
    | '/api/media/$'
    | '/api/newsletter/click'
    | '/api/newsletter/confirm'
    | '/api/newsletter/open'
    | '/api/newsletter/unsubscribe'
    | '/api/newsletter/webhook'
    | '/api/stripe/billing-portal'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/dashboard/newsletters/$newsletterId'
    | '/dashboard/newsletters/new'
    | '/dashboard/pages/new'
    | '/dashboard/posts/new'
    | '/dashboard/users/subscribers'
    | '/dashboard/webhooks/new'
    | '/blog/'
    | '/dashboard/analytics/'
    | '/dashboard/categories/'
    | '/dashboard/comments/'
    | '/dashboard/media/'
    | '/dashboard/newsletters/'
    | '/dashboard/pages/'
    | '/dashboard/posts/'
    | '/dashboard/tags/'
    | '/dashboard/users/'
    | '/dashboard/webhooks/'
    | '/auth/invite/$token'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/dashboard/pages/$pageId/edit'
    | '/dashboard/posts/$postId/edit'
    | '/dashboard/preview/page/$pageId'
    | '/dashboard/preview/post/$postId'
    | '/blog/archive/$year/$month'
    | '/blog/archive/$year/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/about'
    | '/account'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/api/comments'
    | '/api/health'
    | '/dashboard/menus'
    | '/dashboard/messages'
    | '/dashboard/redirects'
    | '/dashboard/settings'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/author/$slug'
    | '/blog/$slug'
    | '/api/auth/$'
    | '/api/comments/$id'
    | '/api/cron/publish'
    | '/api/export/posts'
    | '/api/health/dependencies'
    | '/api/health/readiness'
    | '/api/ingest/$'
    | '/api/media/$'
    | '/api/newsletter/click'
    | '/api/newsletter/confirm'
    | '/api/newsletter/open'
    | '/api/newsletter/unsubscribe'
    | '/api/newsletter/webhook'
    | '/api/stripe/billing-portal'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/dashboard/newsletters/$newsletterId'
    | '/dashboard/newsletters/new'
    | '/dashboard/pages/new'
    | '/dashboard/posts/new'
    | '/dashboard/users/subscribers'
    | '/dashboard/webhooks/new'
    | '/blog'
    | '/dashboard/analytics'
    | '/dashboard/categories'
    | '/dashboard/comments'
    | '/dashboard/media'
    | '/dashboard/newsletters'
    | '/dashboard/pages'
    | '/dashboard/posts'
    | '/dashboard/tags'
    | '/dashboard/users'
    | '/dashboard/webhooks'
    | '/auth/invite/$token'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/dashboard/pages/$pageId/edit'
    | '/dashboard/posts/$postId/edit'
    | '/dashboard/preview/page/$pageId'
    | '/dashboard/preview/post/$postId'
    | '/blog/archive/$year/$month'
    | '/blog/archive/$year'
  id:
    | '__root__'
    | '/_public'
    | '/dashboard'
    | '/_public/$'
    | '/_public/about'
    | '/_public/account'
    | '/_public/auth'
    | '/_public/contact'
    | '/_public/pricing'
    | '/api/comments'
    | '/api/health'
    | '/dashboard/menus'
    | '/dashboard/messages'
    | '/dashboard/redirects'
    | '/dashboard/settings'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/_public/'
    | '/dashboard/'
    | '/_public/auth/forgot-password'
    | '/_public/auth/login'
    | '/_public/auth/register'
    | '/_public/auth/reset-password'
    | '/_public/author/$slug'
    | '/_public/blog/$slug'
    | '/api/auth/$'
    | '/api/comments/$id'
    | '/api/cron/publish'
    | '/api/export/posts'
    | '/api/health/dependencies'
    | '/api/health/readiness'
    | '/api/ingest/$'
    | '/api/media/$'
    | '/api/newsletter/click'
    | '/api/newsletter/confirm'
    | '/api/newsletter/open'
    | '/api/newsletter/unsubscribe'
    | '/api/newsletter/webhook'
    | '/api/stripe/billing-portal'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/dashboard/newsletters/$newsletterId'
    | '/dashboard/newsletters/new'
    | '/dashboard/pages/new'
    | '/dashboard/posts/new'
    | '/dashboard/users/subscribers'
    | '/dashboard/webhooks/new'
    | '/_public/blog/'
    | '/dashboard/analytics/'
    | '/dashboard/categories/'
    | '/dashboard/comments/'
    | '/dashboard/media/'
    | '/dashboard/newsletters/'
    | '/dashboard/pages/'
    | '/dashboard/posts/'
    | '/dashboard/tags/'
    | '/dashboard/users/'
    | '/dashboard/webhooks/'
    | '/_public/auth/invite/$token'
    | '/_public/blog/category/$slug'
    | '/_public/blog/tag/$slug'
    | '/dashboard/pages/$pageId/edit'
    | '/dashboard/posts/$postId/edit'
    | '/dashboard/preview/page/$pageId'
    | '/dashboard/preview/post/$postId'
    | '/_public/blog/archive/$year/$month'
    | '/_public/blog/archive/$year/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiCommentsRoute: typeof ApiCommentsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  RssXmlRoute: typeof RssXmlRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronPublishRoute: typeof ApiCronPublishRoute
  ApiExportPostsRoute: typeof ApiExportPostsRoute
  ApiIngestSplatRoute: typeof ApiIngestSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  ApiNewsletterClickRoute: typeof ApiNewsletterClickRoute
  ApiNewsletterConfirmRoute: typeof ApiNewsletterConfirmRoute
  ApiNewsletterOpenRoute: typeof ApiNewsletterOpenRoute
  ApiNewsletterUnsubscribeRoute: typeof ApiNewsletterUnsubscribeRoute
  ApiNewsletterWebhookRoute: typeof ApiNewsletterWebhookRoute
  ApiStripeBillingPortalRoute: typeof ApiStripeBillingPortalRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/xml': {
      id: '/rss/xml'
      path: '/rss/xml'
      fullPath: '/rss/xml'
      preLoaderRoute: typeof RssXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/redirects': {
      id: '/dashboard/redirects'
      path: '/redirects'
      fullPath: '/dashboard/redirects'
      preLoaderRoute: typeof DashboardRedirectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menus': {
      id: '/dashboard/menus'
      path: '/menus'
      fullPath: '/dashboard/menus'
      preLoaderRoute: typeof DashboardMenusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/account': {
      id: '/_public/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof PublicAccountRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/webhooks/': {
      id: '/dashboard/webhooks/'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks/'
      preLoaderRoute: typeof DashboardWebhooksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tags/': {
      id: '/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags/'
      preLoaderRoute: typeof DashboardTagsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pages/': {
      id: '/dashboard/pages/'
      path: '/pages'
      fullPath: '/dashboard/pages/'
      preLoaderRoute: typeof DashboardPagesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/newsletters/': {
      id: '/dashboard/newsletters/'
      path: '/newsletters'
      fullPath: '/dashboard/newsletters/'
      preLoaderRoute: typeof DashboardNewslettersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media/': {
      id: '/dashboard/media/'
      path: '/media'
      fullPath: '/dashboard/media/'
      preLoaderRoute: typeof DashboardMediaIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/comments/': {
      id: '/dashboard/comments/'
      path: '/comments'
      fullPath: '/dashboard/comments/'
      preLoaderRoute: typeof DashboardCommentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/webhooks/new': {
      id: '/dashboard/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/dashboard/webhooks/new'
      preLoaderRoute: typeof DashboardWebhooksNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/subscribers': {
      id: '/dashboard/users/subscribers'
      path: '/users/subscribers'
      fullPath: '/dashboard/users/subscribers'
      preLoaderRoute: typeof DashboardUsersSubscribersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts/new': {
      id: '/dashboard/posts/new'
      path: '/posts/new'
      fullPath: '/dashboard/posts/new'
      preLoaderRoute: typeof DashboardPostsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pages/new': {
      id: '/dashboard/pages/new'
      path: '/pages/new'
      fullPath: '/dashboard/pages/new'
      preLoaderRoute: typeof DashboardPagesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/newsletters/new': {
      id: '/dashboard/newsletters/new'
      path: '/newsletters/new'
      fullPath: '/dashboard/newsletters/new'
      preLoaderRoute: typeof DashboardNewslettersNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/newsletters/$newsletterId': {
      id: '/dashboard/newsletters/$newsletterId'
      path: '/newsletters/$newsletterId'
      fullPath: '/dashboard/newsletters/$newsletterId'
      preLoaderRoute: typeof DashboardNewslettersNewsletterIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/billing-portal': {
      id: '/api/stripe/billing-portal'
      path: '/api/stripe/billing-portal'
      fullPath: '/api/stripe/billing-portal'
      preLoaderRoute: typeof ApiStripeBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/webhook': {
      id: '/api/newsletter/webhook'
      path: '/api/newsletter/webhook'
      fullPath: '/api/newsletter/webhook'
      preLoaderRoute: typeof ApiNewsletterWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/unsubscribe': {
      id: '/api/newsletter/unsubscribe'
      path: '/api/newsletter/unsubscribe'
      fullPath: '/api/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/open': {
      id: '/api/newsletter/open'
      path: '/api/newsletter/open'
      fullPath: '/api/newsletter/open'
      preLoaderRoute: typeof ApiNewsletterOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/confirm': {
      id: '/api/newsletter/confirm'
      path: '/api/newsletter/confirm'
      fullPath: '/api/newsletter/confirm'
      preLoaderRoute: typeof ApiNewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/click': {
      id: '/api/newsletter/click'
      path: '/api/newsletter/click'
      fullPath: '/api/newsletter/click'
      preLoaderRoute: typeof ApiNewsletterClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/$': {
      id: '/api/ingest/$'
      path: '/api/ingest/$'
      fullPath: '/api/ingest/$'
      preLoaderRoute: typeof ApiIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/readiness': {
      id: '/api/health/readiness'
      path: '/readiness'
      fullPath: '/api/health/readiness'
      preLoaderRoute: typeof ApiHealthReadinessRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/dependencies': {
      id: '/api/health/dependencies'
      path: '/dependencies'
      fullPath: '/api/health/dependencies'
      preLoaderRoute: typeof ApiHealthDependenciesRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/export/posts': {
      id: '/api/export/posts'
      path: '/api/export/posts'
      fullPath: '/api/export/posts'
      preLoaderRoute: typeof ApiExportPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/publish': {
      id: '/api/cron/publish'
      path: '/api/cron/publish'
      fullPath: '/api/cron/publish'
      preLoaderRoute: typeof ApiCronPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments/$id': {
      id: '/api/comments/$id'
      path: '/$id'
      fullPath: '/api/comments/$id'
      preLoaderRoute: typeof ApiCommentsIdRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/author/$slug': {
      id: '/_public/author/$slug'
      path: '/author/$slug'
      fullPath: '/author/$slug'
      preLoaderRoute: typeof PublicAuthorSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/reset-password': {
      id: '/_public/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof PublicAuthResetPasswordRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/register': {
      id: '/_public/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/forgot-password': {
      id: '/_public/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/dashboard/preview/post/$postId': {
      id: '/dashboard/preview/post/$postId'
      path: '/preview/post/$postId'
      fullPath: '/dashboard/preview/post/$postId'
      preLoaderRoute: typeof DashboardPreviewPostPostIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preview/page/$pageId': {
      id: '/dashboard/preview/page/$pageId'
      path: '/preview/page/$pageId'
      fullPath: '/dashboard/preview/page/$pageId'
      preLoaderRoute: typeof DashboardPreviewPagePageIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts/$postId/edit': {
      id: '/dashboard/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/dashboard/posts/$postId/edit'
      preLoaderRoute: typeof DashboardPostsPostIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pages/$pageId/edit': {
      id: '/dashboard/pages/$pageId/edit'
      path: '/pages/$pageId/edit'
      fullPath: '/dashboard/pages/$pageId/edit'
      preLoaderRoute: typeof DashboardPagesPageIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/blog/tag/$slug': {
      id: '/_public/blog/tag/$slug'
      path: '/blog/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof PublicBlogTagSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/category/$slug': {
      id: '/_public/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof PublicBlogCategorySlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/invite/$token': {
      id: '/_public/auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/auth/invite/$token'
      preLoaderRoute: typeof PublicAuthInviteTokenRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/blog/archive/$year/': {
      id: '/_public/blog/archive/$year/'
      path: '/blog/archive/$year'
      fullPath: '/blog/archive/$year/'
      preLoaderRoute: typeof PublicBlogArchiveYearIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/archive/$year/$month': {
      id: '/_public/blog/archive/$year/$month'
      path: '/blog/archive/$year/$month'
      fullPath: '/blog/archive/$year/$month'
      preLoaderRoute: typeof PublicBlogArchiveYearMonthRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicAuthRouteChildren {
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicAuthResetPasswordRoute: typeof PublicAuthResetPasswordRoute
  PublicAuthInviteTokenRoute: typeof PublicAuthInviteTokenRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthResetPasswordRoute: PublicAuthResetPasswordRoute,
  PublicAuthInviteTokenRoute: PublicAuthInviteTokenRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAccountRoute: typeof PublicAccountRoute
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicContactRoute: typeof PublicContactRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthorSlugRoute: typeof PublicAuthorSlugRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicBlogCategorySlugRoute: typeof PublicBlogCategorySlugRoute
  PublicBlogTagSlugRoute: typeof PublicBlogTagSlugRoute
  PublicBlogArchiveYearMonthRoute: typeof PublicBlogArchiveYearMonthRoute
  PublicBlogArchiveYearIndexRoute: typeof PublicBlogArchiveYearIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicAboutRoute: PublicAboutRoute,
  PublicAccountRoute: PublicAccountRoute,
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicContactRoute: PublicContactRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthorSlugRoute: PublicAuthorSlugRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicBlogCategorySlugRoute: PublicBlogCategorySlugRoute,
  PublicBlogTagSlugRoute: PublicBlogTagSlugRoute,
  PublicBlogArchiveYearMonthRoute: PublicBlogArchiveYearMonthRoute,
  PublicBlogArchiveYearIndexRoute: PublicBlogArchiveYearIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardRouteChildren {
  DashboardMenusRoute: typeof DashboardMenusRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardRedirectsRoute: typeof DashboardRedirectsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardNewslettersNewsletterIdRoute: typeof DashboardNewslettersNewsletterIdRoute
  DashboardNewslettersNewRoute: typeof DashboardNewslettersNewRoute
  DashboardPagesNewRoute: typeof DashboardPagesNewRoute
  DashboardPostsNewRoute: typeof DashboardPostsNewRoute
  DashboardUsersSubscribersRoute: typeof DashboardUsersSubscribersRoute
  DashboardWebhooksNewRoute: typeof DashboardWebhooksNewRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardCommentsIndexRoute: typeof DashboardCommentsIndexRoute
  DashboardMediaIndexRoute: typeof DashboardMediaIndexRoute
  DashboardNewslettersIndexRoute: typeof DashboardNewslettersIndexRoute
  DashboardPagesIndexRoute: typeof DashboardPagesIndexRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardTagsIndexRoute: typeof DashboardTagsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardWebhooksIndexRoute: typeof DashboardWebhooksIndexRoute
  DashboardPagesPageIdEditRoute: typeof DashboardPagesPageIdEditRoute
  DashboardPostsPostIdEditRoute: typeof DashboardPostsPostIdEditRoute
  DashboardPreviewPagePageIdRoute: typeof DashboardPreviewPagePageIdRoute
  DashboardPreviewPostPostIdRoute: typeof DashboardPreviewPostPostIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMenusRoute: DashboardMenusRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardRedirectsRoute: DashboardRedirectsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardNewslettersNewsletterIdRoute: DashboardNewslettersNewsletterIdRoute,
  DashboardNewslettersNewRoute: DashboardNewslettersNewRoute,
  DashboardPagesNewRoute: DashboardPagesNewRoute,
  DashboardPostsNewRoute: DashboardPostsNewRoute,
  DashboardUsersSubscribersRoute: DashboardUsersSubscribersRoute,
  DashboardWebhooksNewRoute: DashboardWebhooksNewRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardCommentsIndexRoute: DashboardCommentsIndexRoute,
  DashboardMediaIndexRoute: DashboardMediaIndexRoute,
  DashboardNewslettersIndexRoute: DashboardNewslettersIndexRoute,
  DashboardPagesIndexRoute: DashboardPagesIndexRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardTagsIndexRoute: DashboardTagsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardWebhooksIndexRoute: DashboardWebhooksIndexRoute,
  DashboardPagesPageIdEditRoute: DashboardPagesPageIdEditRoute,
  DashboardPostsPostIdEditRoute: DashboardPostsPostIdEditRoute,
  DashboardPreviewPagePageIdRoute: DashboardPreviewPagePageIdRoute,
  DashboardPreviewPostPostIdRoute: DashboardPreviewPostPostIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiCommentsRouteChildren {
  ApiCommentsIdRoute: typeof ApiCommentsIdRoute
}

const ApiCommentsRouteChildren: ApiCommentsRouteChildren = {
  ApiCommentsIdRoute: ApiCommentsIdRoute,
}

const ApiCommentsRouteWithChildren = ApiCommentsRoute._addFileChildren(
  ApiCommentsRouteChildren,
)

interface ApiHealthRouteChildren {
  ApiHealthDependenciesRoute: typeof ApiHealthDependenciesRoute
  ApiHealthReadinessRoute: typeof ApiHealthReadinessRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthDependenciesRoute: ApiHealthDependenciesRoute,
  ApiHealthReadinessRoute: ApiHealthReadinessRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiCommentsRoute: ApiCommentsRouteWithChildren,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  RssXmlRoute: RssXmlRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronPublishRoute: ApiCronPublishRoute,
  ApiExportPostsRoute: ApiExportPostsRoute,
  ApiIngestSplatRoute: ApiIngestSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  ApiNewsletterClickRoute: ApiNewsletterClickRoute,
  ApiNewsletterConfirmRoute: ApiNewsletterConfirmRoute,
  ApiNewsletterOpenRoute: ApiNewsletterOpenRoute,
  ApiNewsletterUnsubscribeRoute: ApiNewsletterUnsubscribeRoute,
  ApiNewsletterWebhookRoute: ApiNewsletterWebhookRoute,
  ApiStripeBillingPortalRoute: ApiStripeBillingPortalRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
